package de.shelp.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-03T15:18:07.249+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://integration.shelp.de/", name = "FriendIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface FriendIntegration {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "acceptFriendship", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.AcceptFriendship")
    @WebMethod
    @ResponseWrapper(localName = "acceptFriendshipResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.AcceptFriendshipResponse")
    public de.shelp.integration.ReturnCodeResponse acceptFriendship(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFriends", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.GetFriends")
    @WebMethod
    @ResponseWrapper(localName = "getFriendsResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.GetFriendsResponse")
    public de.shelp.integration.FriendsResponse getFriends(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws SessionNotExistException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteFriendship", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.DeleteFriendship")
    @WebMethod
    @ResponseWrapper(localName = "deleteFriendshipResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.DeleteFriendshipResponse")
    public de.shelp.integration.ReturnCodeResponse deleteFriendship(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deniedFriendship", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.DeniedFriendship")
    @WebMethod
    @ResponseWrapper(localName = "deniedFriendshipResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.DeniedFriendshipResponse")
    public de.shelp.integration.ReturnCodeResponse deniedFriendship(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addFriend", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.AddFriend")
    @WebMethod
    @ResponseWrapper(localName = "addFriendResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.AddFriendResponse")
    public de.shelp.integration.ReturnCodeResponse addFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
