package de.shelp.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-02T15:14:25.537+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://integration.shelp.de/", name = "RatingIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface RatingIntegration {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRatings", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.GetRatings")
    @WebMethod
    @ResponseWrapper(localName = "getRatingsResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.GetRatingsResponse")
    public de.shelp.integration.RatingResponse getRatings(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createRating", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.CreateRating")
    @WebMethod
    @ResponseWrapper(localName = "createRatingResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.CreateRatingResponse")
    public de.shelp.integration.ReturnCodeResponse createRating(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );
}
