
package de.shelp.integration;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-03T15:18:07.155+02:00
 * Generated source version: 2.7.13
 */

@WebFault(name = "SessionNotExistException", targetNamespace = "http://integration.shelp.de/")
public class SessionNotExistException_Exception extends Exception {
    
    private de.shelp.integration.SessionNotExistException sessionNotExistException;

    public SessionNotExistException_Exception() {
        super();
    }
    
    public SessionNotExistException_Exception(String message) {
        super(message);
    }
    
    public SessionNotExistException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SessionNotExistException_Exception(String message, de.shelp.integration.SessionNotExistException sessionNotExistException) {
        super(message);
        this.sessionNotExistException = sessionNotExistException;
    }

    public SessionNotExistException_Exception(String message, de.shelp.integration.SessionNotExistException sessionNotExistException, Throwable cause) {
        super(message, cause);
        this.sessionNotExistException = sessionNotExistException;
    }

    public de.shelp.integration.SessionNotExistException getFaultInfo() {
        return this.sessionNotExistException;
    }
}
