package de.shelp.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-05-21T13:49:17.164+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://integration.shelp.de/", name = "UserIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface UserIntegration {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.LogoutResponse")
    public de.shelp.integration.ReturnCodeResponse logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "regUser", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.RegUser")
    @WebMethod
    @ResponseWrapper(localName = "regUserResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.RegUserResponse")
    public de.shelp.integration.UserResponse regUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.LoginResponse")
    public de.shelp.integration.UserResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchUsers", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.SearchUsers")
    @WebMethod
    @ResponseWrapper(localName = "searchUsersResponse", targetNamespace = "http://integration.shelp.de/", className = "de.shelp.integration.SearchUsersResponse")
    public de.shelp.integration.UsersResponse searchUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
